# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

#SMTP_HOST: "powercozmo.com"
SMTP_HOST: "powercozmo.herokuapp.com"
DATABASE_NAME: 'powercozmo'
DB_USER_NAME: 'root'
DB_PASSWORD: '123456'
#SMTP_ADDRESS: 'gmail.com'
SMTP_ADDRESS: 'smtp.sparkpostmail.com'
#SMTP_DOMAIN: 'powercozmo.com'
SMTP_DOMAIN: 'powercozmo.herokuapp.com'
#SMTP_USERNAME: 'developer@brsoftech.com'
SMTP_USERNAME: 'SMTP_Injection'
#SMTP_PASSWORD: 'brsoftech@123'
SMTP_PASSWORD: 'c0f1a28e406778b7b7301026baa9fb90cdabda2d'
SUPER_ADMIN_EMAIL: 'narendra.prajapat@brsoftech.org' 

DEFAULT_FROM_EMAIL: 'info@powercozmo.com'
FB_APP_ID: "594255860733170"
